### ISSUE TITLE
이슈 레이블 관리

### ISSUE THREAD

**Issue by JhoLee** [Aquilaegis/aquilaegis.github.io#1]
이슈 레이블 관리

**Comment by Sihan-Son** [comment]
이 이슈는 뭘 하면 되는 이슈인가요?

**Comment by JhoLee** [comment]
@Sihan-Son 기존에 존재하는 레이블의 이름과 설명을,  우리가 사용할 만한 레이블로 수정 부탁해요

**Comment by JhoLee** [comment]
이거 organization 전체 이슈에서 다뤄야 할 이슈인데... 잘못 만들었네요.
